"""detail column was added to cart_item table

Revision ID: 3f3ef7a43470
Revises: 387c7a1657f7
Create Date: 2024-07-11 05:16:55.051460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f3ef7a43470'
down_revision: Union[str, None] = '387c7a1657f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_item', sa.Column('detail', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart_item', 'detail')
    # ### end Alembic commands ###
