"""brand column added to Cart Item

Revision ID: 6615d951670b
Revises: 8e393d2d3793
Create Date: 2024-07-22 04:22:45.340547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6615d951670b'
down_revision: Union[str, None] = '8e393d2d3793'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_item', sa.Column('brand', sa.String(length=6), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart_item', 'brand')
    # ### end Alembic commands ###
