"""who_accept column added to the order table

Revision ID: 8e393d2d3793
Revises: 3f7269bc9d68
Create Date: 2024-07-16 06:35:36.817444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e393d2d3793'
down_revision: Union[str, None] = '3f7269bc9d68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('who_accept', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'who_accept')
    # ### end Alembic commands ###
