"""client and manager tables created

Revision ID: a28ee295ef4d
Revises: 6615d951670b
Create Date: 2024-07-24 09:31:32.488907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a28ee295ef4d'
down_revision: Union[str, None] = '6615d951670b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manager_model',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(length=13), nullable=False),
    sa.Column('login', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_index(op.f('ix_manager_model_id'), 'manager_model', ['id'], unique=False)
    op.create_index(op.f('ix_manager_model_phone'), 'manager_model', ['phone'], unique=True)
    op.create_table('client_model',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(length=13), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['manager_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_model_id'), 'client_model', ['id'], unique=False)
    op.create_index(op.f('ix_client_model_phone'), 'client_model', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_model_phone'), table_name='client_model')
    op.drop_index(op.f('ix_client_model_id'), table_name='client_model')
    op.drop_table('client_model')
    op.drop_index(op.f('ix_manager_model_phone'), table_name='manager_model')
    op.drop_index(op.f('ix_manager_model_id'), table_name='manager_model')
    op.drop_table('manager_model')
    # ### end Alembic commands ###
